### ISSUE TITLE
Failure to load blueprint strings with textplate in them

### ISSUE THREAD

**Issue by OwenDurni** [redruin1/factorio-draftsman#101]
**Describe the bug**
Make a blueprint containing entities from the textplate mod.

**Current Behavior**
Draftsman throws an InvalidEntityError from entity.py (`new_entity` function)

**Expected behavior**
Draftsman supports blueprints with this entity type.

**Additional context**
Textplates use the SimpleEntityWithForce factorio prototype. It seems reasonable that draftsman would allow placing these entities and modifying their location. It seems unreasonable to be able to do much of anything else.

Draftsman may need custom support for textplate entities because of how they handle the variations for different characters? I'm not too sure.

**Please also include the following:**
Draftsman version: `1.0.6`
Python version: `3.9`

I personally would not consider this a very high priority. It does seem useful to be able to include documentation in the form of textplate in the blueprint itself (although you can emulate this with constant combinators in vanilla).

**Comment by redruin1** [comment]
Thanks for the report, I honestly forgot that this prototype was used. In a similar vein I might also have to create classes for `SimpleEntityWithOwner`, and perhaps more depending on which others I've missed. This is fairly critical in my estimation, so I'll actually probably release a minor version with the missing classes implemented soonish:tm:.

**Comment by OwenDurni** [comment]
Can confirm that this fixes the reported issue with textplate.

If relevant, I do get the following warning on the console when calling draftsman.blueprintable.Blueprint(<exported blueprint string containing textplate>)

> DraftsmanWarning: <class 'draftsman.prototypes.simple_entity_with_force.SimpleEntityWithForce'> has no attribute 'direction'

**Comment by redruin1** [comment]
Can text plate entities be rotated?

**Comment by redruin1** [comment]
Horrifyingly, the answer is both yes and no. They *can* be rotated and own a "direction" key, but doing so is *invisible* in-game; the right character in the following blueprint is rotated once clockwise:
![image](https://github.com/redruin1/factorio-draftsman/assets/25079873/b8db9524-9c94-4618-bc96-1b7f30c74323)
```
0eNqdkN0KgzAMRt8l11Vmp6vrq4wxqoYRqLW0dSjSd1/Vm/1cDHaZcPKdJAs0ekTryASQC1A7GA/ysoCnu1F67YXZIkiggD0wMKpfq4BTsFoFzHyvtM7awVp0EBmQ6XACWcQrAzSBAuGeuBXzzYx9k0hZ/MpiYAefxgezbrFGloe8YjCDFDyvkuqhHKkdOEb2ZeB/GPi7oSOH7Q7wD186b3uJfPlgQtD5Ha+LUpy5EKeyELyO8Qmd5ng+
```
Positively evil. I assume then that entities of these types can be rotated in other mods, but in this case it has no effect. Do you know of any other mods that use this prototype that I can cross reference, or should I just cave and add a direction parameter to both `SimpleEntityWithOwner` and `SimpleEntityWithForce`?

**Comment by OwenDurni** [comment]
A friend wrote this mod https://mods.factorio.com/mod/arrowplates which makes sure that the 8-directional arrow textplates properly rotate when the textplate is rotated.

I'm not aware of other mods off-hand where this matters.

**Comment by falsedrow** [comment]
The prototypes are rotatable and do have direction. The textplates in particular don't have a four way sprite, so you can't see the result visually, but they do track their direction.

I wanted to make all of the textplates rotate but decided that I didn't want to deal with all the new graphics without talking to the mod author first :-)

**Comment by redruin1** [comment]
Noted. I'll make sure both prototypes are `Directional` then.
