### ISSUE TITLE
Circuit connections inside group within a blueprint fail to create blueprint string

### ISSUE THREAD

**Issue by elswindle** [redruin1/factorio-draftsman#16]
After adding circuit connections to entities within a group and adding that `Group` to a `Blueprint`, when I try to convert the blueprint to a string, I get a `ValueError` that the connected entity is not in the list.  More specifically, I load up a blueprint and add a few circuit connections (at this point, the blueprint is still good and can export to string with no issue).  I then create a `Group` from the entities of the blueprint.  I add the `Group` to a new `Blueprint` and try to create the string from it, but it breaks.  If I do not make the circuit connections, there's no problem and can import it to Factorio no problem.  I've attached my code and the error code:

`Exception has occurred: ValueError
<LogisticRequestContainer '5'>{'name': 'logistic-chest-requester', 'position': {'x': 43.5, 'y': -0.5}, 'connections': {'1': {'green': [{'entity_id': <Association to Inserter with id '0'>}], 'red': [{'entity_id': <Association to Inserter with id '4'>}]}}} is not in list`

    # Labs bp
    bp_str = "0eJy1ldtugzAMht/F10kFAUrhcq8xTRMHq4sGgZFQDVW8+5K2q+ja0ZCtVxzsfL/j2PEe8qrHtuNCQboHXjRCQvq8B8m3IqvMPzW0CClwhTUQEFltvnLMtCuMBLgo8RNSfyR3F1VZPlnBxhcCKBRXHI+aEzcCbSO1RWtomvam/ioiMOhlq8gwNFgaU9s1ZV8ovuNqoLV+r5AGBn5iD6+ir3PsThFehn+tEpxUoksV2SKW83hmg/ec8YEFnjnTwwldqqx4p1xI7JS2/b4J7yDzgxQtIM2C1hNQ1Wy5VLygxRtKRTv86PVzNjh6Exo7QeeZG5fcmXLWqJJ3WBzt4RU4cUilDdf3plm41WzfvWbawbHZrLrtHPV6ccX6Nv3G/sC3aTjKLitjkUBoewruN160JEcOW1jf2wL9h0qKl9zbLie9eejV6iePLVTmmTl6GLTpZJgT2GEnDwps44dxwuKQJUmQ+MQcFeopDU9n73H8AlTBmZE="
    bp = Blueprint(bp_str)
    bp2 = Blueprint(bp_str)

    new_id = 0
    inserters = bp.find_entities_filtered(type='inserter')
    for ins in inserters:
        ins.id = str(new_id)
        new_id += 1
        base_pos = ins.position
        pos1 = (base_pos['x'], base_pos['y']+1)
        nb = bp.find_entities_filtered(position=pos1)
        if(nb[0].type == 'logistic-container'): 
            nb[0].id = str(new_id)
            new_id += 1
            bp.add_circuit_connection('red', ins.id, nb[0].id)
        pos1 = (base_pos['x'], base_pos['y']-1)
        nb = bp.find_entities_filtered(position=pos1)
        if(nb[0].type == 'logistic-container'):
            nb[0].id = str(new_id)
            new_id += 1
            bp.add_circuit_connection('green', ins.id, nb[0].id)

    g1 = Group('g1', entities=bp2.entities)
    g2 = Group('g2', entities=bp.entities)

    for entity in g2.entities:
        entity.position['x'] += 9
    bp3 = Blueprint()
    # bp3.entities.append(g1)
    bp3.entities.append(g2)

    print(bp3.to_string())

**Comment by elswindle** [comment]
A quick addition to this, but this error is not limited to circuit connections, but power connections as well.  That's probably a given, but better to be thorough.

**Comment by elswindle** [comment]
Having a constructor for `Group` that accepts a string would be nice since it'll save computation time converting from a blueprint to a group.  That will be good considering my comment in #20.

**Comment by redruin1** [comment]
Alright, I'll put it in now. What attributes would you like to acquire from a blueprint string? Should it just be the entities, or is there extra information that you would like to extract?

**Comment by elswindle** [comment]
I think entities is all I should need.  If not, I can just override the `__init__` function and grab more data.  I feel like the only other thing I might need is some location data, like local/absolute position.  I haven't gotten to that point yet.
