### ISSUE TITLE
`OverlappingObjectsWarning` being issued when they should not

### ISSUE THREAD

**Issue by redruin1** [redruin1/factorio-draftsman#27]
There are a number of cases where `OverlappingObjectsWarning`s are issued to the user when they're not valid:

1. When `StraightRail` or `CurvedRail` entities overlap other `StraightRail` or `CurvedRail` entities
2. When `RailSignal`s or `RailChainSignal`s are placed next to a diagonal straight rail (the collision box is not rotated 45 degrees because currently we operate exclusively with AABBs)

Feel free to add more in the comments if you come across any.

**Comment by elswindle** [comment]
Any entity that is within the bounding box of the `CurvedRail` will throw the error despite being a valid location.  This is similar to 2 since it is using an AABB collision box for a curved object.

**Comment by redruin1** [comment]
Both `CurvedRail` and diagonally placed `StraightRails` now have correct collision boxes, so this should no longer be an issue. I think these were the only real offenders, so I'm going to tentatively close this issue, though if anyone finds more examples feel free to reopen.
