### ISSUE TITLE
KeyError on draftsman-update using the Miniloader mod

### ISSUE THREAD

**Issue by JoachimGeelen** [redruin1/factorio-draftsman#9]
**Environment**
Windows 10
Factorio 1.1.57
draftsmen 0.9.2
Python 3.10.1 

**Error:**
`Traceback (most recent call last): `
`File "C:\..\Python310\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None,`
`File "C:\..\Python310\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\..\Python310\Scripts\draftsman-update.exe\__main__.py", line 7, in <module>`
`File "C:\..\Python310\lib\site-packages\draftsman\env.py", line 1657, in main update(verbose=args.verbose, no_mods=args.no_mods)` 
`File "C:\..\Python310\lib\site-packages\draftsman\env.py", line 1623, in update extract_entities(lua, data_location, verbose)`
`File "C:\..\Python310\lib\site-packages\draftsman\env.py", line 528, in extract_entities inserter["order"] = items[inserter_name]["order"]`
`KeyError: 'fast-miniloader-inserter'`

I've tested with and without other additional mods and draftsman-update produces the same error whenever the **[Miniloader](https://mods.factorio.com/mod/miniloader)** mod is included. There are no dependency errors in the in-game mod menu.

**Comment by redruin1** [comment]
Should be fixed now. I assumed that all inserter entities would have an associated item with them; I see now this was a silly assumption. Try running `pip install factorio-draftsman --upgrade` to install `0.9.3` and see if that resolves the issue.

**Comment by redruin1** [comment]
On a similar not, I'm going to revamp entity extraction a little to make this a little more predictable and somewhat less likely to happen in the future, though that implementation will probably wait until `0.9.4`.
